config-version: 2

name: "dbt_jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

profile: dwh_test # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

models:
  jaffle_shop:
    +schema: dbt_jaffle_shop
    +grants:
      select: ['viewers_all', 'writers_all']
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    core:
      +materialized: table
    marts:
      +materialized: table

seeds:
  +schema: stage_shop
  +grants:
    select: ['viewers_all', 'writers_all']
